src/array.c, src/sdb.h
Second part of the split pull request #67. Completes #59.
Implemented `sdb_array_sort` and `sdb_array_sort_num`. Will add `sdb_array_add_sorted` later. @alvarofe can maybe already use these.
=> Added sdb_array_sort() and sdb_array_sort_num()

src/cdb_make.c
Cygwin doesn't have _aligned_malloc() function.
=> Fix Cygwin build

src/cdb_make.c
<malloc.h> is needed for _aligned_malloc() function on Windows.
=> Fix building for the MinGW

src/cdb.c, src/cdb_make.c, src/cdb_make.h, src/sdb.c
The trick is to compute the subtable length n_i, 0 <= i <= 255, using
the subtable pointers p_i and p_{i+1}. Observe that
n_i = (p_{i+1} - p_i) / L, where L is the slot length.
So let's not waste 1024 bytes of space to encode n_i.
=> Reduce CDB header size (2048 bytes -> 1024 bytes)

src/cdb_make.c
As per Issue #75, for MinGW use _aligned_free() instead of free() for memory allocated with _aligned_malloc()
=> MinGW: use _aligned_free() instead of free()

src/sdb.c
Now `sdb_get_len()` is just a wrapper for `sdb_const_get_len()` that strdups the result.
Both functions looked almost the same, just a few changes that were in one function but not the other which are now merged.
=> Merge the implementation of sdb_get_len() with sdb_const_get_len()

test/collision.sh
the hashtable underlying sdb doesn't handle collisions, add a test for
this.
=> add failing test for collisions in the hashtable

src/ht.c
I'd guess this improvement is also welcomed to this repo. This was already merged to r2 in order to fix a segfault that occurred as a result of careless use of hashtable entries (without specifically checking for deleted entries that should be treated as empty in spite of `entry->data != NULL`). See https://github.com/radare/radare2/pull/5252 for full explanation.
=> Improve ht.c's handling of removed entries

src/num.c
=> fixing segfault in sdb_bool_get

src/ht.c, test/Makefile, test/unit/Makefile, test/unit/minunit.h, test/unit/run.sh, test/unit/test_hash.c
I started adding some unit testing for SDB.... first test, and it looks like at the moment the whole thing should be completely broken :( :( Indeed key and value are always the same when inserted through `ht_hash_insert`. 
What I would like to do is to make this HT implementation a little bit more generic, so that we can use that in r2 easily for other needs and not only for string-string pairs.
=> Fix value always equals to key issue

src/util.c
Self-explanatory.
Pretty sure it's a typo...
=> Correct typo in src/util.c: USE_MONOTINIC_CLOCK -> USE_MONOTONIC_CLOCK

meson.build
It allows to install sdb separately with meson and, later, to use sdb as a meson subproject in radare2.
=> meson.build: read sdb_version from config and make it main project

.gitignore, src/query.c, src/sdb.c, src/sdbht.c, src/sdbht.h, test/unit/test_hash.c
~~This PR is based on https://github.com/radare/sdb/pull/158 .~~
~~The only difference is the last commits.~~ The commit introduces helper macros in the sdbht.h file to access SdbKv->key/value/key_len/value_len since they are fields of the "base structure" HtKv. In another PR i'm going to change those fields, so I want to introduce these helpers to make those change easier.
=> Sdbkv refactor

src/base64.c
Solaris has its own b64_encode and b64_decode functions, which the ones here can conflict with:
```
Standard C Library Functions                                    b64_encode(3C)
NAME
b64_encode,  b64_decode,  b32_encode,  b32_decode - encode and decode a
string in base64 or base32
SYNOPSIS
#include <string.h>
ssize_t b64_encode(char restrict *outbuf, size_t outbufsz,
const void restrict *inbuf, size_t inbufsz,
const char *alphabet, uint64_t flags);
ssize_t b64_decode(void *outbuf, size_t outbufsz,
const char *inbuf, const char *alphabet, uint64_t flags);
```
=> Fix b64_* for Solaris

src/disk.c
Related to radareorg/cutter#589
fixed heap corruption in SDB
fixed proper project saving on windows
=> Windows&Unicode fix, fixed heap corruption

meson.build
*Explicit is better than implicit*.
This PR:
* Use Meson 0.47.0 to use install_man
* Prefer using configuration() than manually generating header file
* Install sdb man file
=> meson: Do not use glob with Meson

src/sdb.c
This  PR fixes closing of a file descriptor which is already closed (causes `abort()` on windows) so radare2 just crashed before.
Sample to reproduce is attached in an archive, password `infected`
[CDPLAYER.EXE.zip](https://github.com/radare/sdb/files/2963751/CDPLAYER.EXE.zip)
How to reproduce a crash:
- unpack and open provided file with radare2 like `radare2.exe CDPLAYER.EXE.bad` on **Windows**
- crash
After fix it should smoothly open such file:
=> Fix crash on Windows due to closing already closed file descriptor

meson.build, test/bench/meson.build, test/bench/prof.c
Example of using: `meson test --benchmark --verbose -C build`
=> Add benchmark suites to meson

src/ls.c, test/unit/test_ls.c
Merge sort uses cmp (a, b) < 0 for its first test branch, and insertion
sort cmp (a, b) > 0 ; which means the 0 boundary goes in one case in one
branch, and in the other sort function in the other branch.
We keep the semantics of the insertion sort, it makes it possible to
support compare function that return true/false instead of a distance
between items.
Add a test that was previously failing for merge sort, but working with
insertion sort, although the function is not exposed, it only triggers
at > 43 elements.
The main difference is the test function that sends true/false instead
of a difference between two integers.
**Test plan**
See included test
N/A
=> Bring merge sort and insertion sort cmp function semantics together

src/json/rangstr.h
To be in sync with r2.
This was changed in https://github.com/radareorg/radare2/pull/17430
=> Change RangstrType to unsigned int

meson.build, meson_options.txt
Similar to radare2, it allows to install sdb in a local path and set rpath so that you don't have to mess with LD_LIBRARY_PATH & co.
=> Add support for `local` meson option

src/text.c, test/unit/test_sdb.c
This happens because `load_flush_line()` will write a zero-byte just after the line. Most of the time, this just overwrites the `\n` but at the very end of the file, it writes one byte after the allocated buffer. With mmap this usually stays undetected because the whole page is allocated, but with mmap disabled and asan it shows even in the current tests.
There would be different ways to fix this:
* Always pass a 1-byte bigger buffer to `sdb_text_load_buf()`: If done directly like this, a user of the function would have to be aware of that and it goes against everything we are used to when we have an additional size argument. Alternatively the string may always be forced to be zero-terminated and the size removed, but that would imply a lot of additional checks and issues, or a strlen …
=> Fix OOB write in text parsing

src/sdb.h
It allows compilers like GCC or Clang to check the validity of `sdb_fmt()` arguments count and type, according to the used format string.
**Test plan**
All green
=> Add printf-format arguments check for sdb_fmt

meson.build
sdb binary may be used by the build machine to compile .sdb files. In
that case it is necessary to have the sdb binary compiled for the build
machine and not for the host one, as it is by default.
**Test plan**
Create a file `cross-file.txt` with:
```
[properties]
exe_wrapper = 'wine'
```
and then run `meson build --cross-file cross-file.txt ; ninja -C build`. It should work and it should create another binary called sdb_native.
None
=> Compile a native sdb binary when cross building

src/sdb.c
Change arguments type from int to bool. Those are internal static function, so no other code could possibly be affected. There are booleans all over the place in that file, so we are not losing any portability.
PS Editing raw `*.patch`es to match new paths is a surprisingly valid technique.
**Test plan**
None
Originally (mistakenly) posted at: https://github.com/radareorg/radare2/pull/18120
=>  SDB: In Soviet Russia, C has booleans ##refactor

src/ht_inc.c
Added a missing null check in ht_(find_kv) in ht_inc.c
While fuzzing I caused this nullpointer dereference and while looking for the root cause I realized that a check is missing.
**Test plan**
I really just added an if to avoid a null pointer dereference.
None
=> Added missing null check

src/util.c
make a clearer separation between temporary and allocated string buffer
eleminating gcc warning about function may return address of local variable
**Checklist**
See above. It's a cosmetic bugfix. Nothing new to document or add.
=> Rework sdb_itoa buffer management to silence GCC warning

Makefile, src/fmt.c, src/journal.c, src/json/js0n.c, src/lock.c, src/query.c, src/sdb.c, src/sdb.h, src/util.c, test/hook2.c, test/unit/test_sdb.c
**Checklist**
This makes sdb thread-safe without the need for TLS.
* Nuke sdb_fmt
* Mark goto tables as const
* Mark lookup table as const
* Move nextcas into SdbKv
* Remove global hook (cannot be used without TLS, but we want to avoid
that)
* Fix lock path to not use a static buffer
=> Remove TLS and make sdb thread-safe

src/cdb.c, src/dict.c, src/dict.h, src/disk.c, src/json.c, src/json/path.c, src/ls.c, src/query.c, src/sdb.c, src/sdb.h, src/util.c, test/unit/test_dict.c
* fputs(stdout) is still pending to be removed, but this requires breaking API and ABI
**Checklist**
=> Remove all calls to eprintf from library apis

TODO, include/sdb/asserts.h, include/sdb/sdb.h
=> Add debug assert macros

config.mk, include/sdb/types.h
- If _XOPEN_SOURCE macro is defined, SIZE_MAX disappears on AIX.
So, disable it.
- INT32_MAX macro doesn't exist, so patch it up.
**Checklist**
=> Fix AIX support

include/sdb/buffer.h, src/buffer.c, src/cdb_make.c
**Checklist**
libmagic defines the buffer_init symbol, so I've renamed it to buffer_initialize. Honestly, neither libmagic nor sdb should be using this symbol name since it's so generic. So perhaps we could rename all of these `buffer_` methods to `sdb_buffer_` if that works.
=> Fix symbol conflicts with libmagic
