src/cdb.c
=> cdb.c: Untaint value for coverity

src/main.c, src/ns.c
fix some deadcode and resource leaks
=> fix COV 1365298 1365299 1365300

src/Makefile, src/ht.c, src/ht.h, src/sdb.c, src/sdb.h, src/sdbht.c, src/sdbht.h, test/unit/test_array.c, test/unit/test_hash.c
It pass the tests in sdb but I have to test the general implementation in ht.c so not merge yet.
=> Make some change in hashtable implementation

src/array.c, src/json.c, src/json/indent.c, src/json/path.c, src/json/rangstr.c, src/main.c, src/query.c
This pull requested is a new version of #132, I applied the fixes suggested.
=> Fix several bugs found with AFL

src/cdb.c, src/json/js0n.c, src/sdb.h, src/types.h, src/util.c
- avoid linkage missing functions
=> fixed some files to compile with msvc

src/sdbht.h
This PR is a follow up to https://github.com/radare/radare2/pull/7972
=> Use void in prototypes

src/array.c, src/ht.c
=> fixes warnings generated by -Wsign-compare

src/sdb.c
=> Fix null deref in sdb_exists() (Fix #182)

src/ht_inc.c, src/ht_inc.h, test/unit/test_hash.c
This is useful in https://github.com/radare/radare2/blob/master/libr/flag/flag.c#L627
=> Add Ht update_key API

.appveyor.yml
@radare please also enable webhook for SDB: https://ci.appveyor.com/api/github/webhook?id=h8nhvvulcu8t8m5x
=> Trying to build SDB with AppVeyor

.gitignore, meson.build, src/Makefile, src/diff.c, src/main.c, src/sdb.h, test/unit/test_diff.c
=> Add better diffing

bindings/nodejs/json/genjson.js
Local variable i.
**Test plan**
...
...
=> Fix a LGTM alert

src/query.c
Step forward to fix LGTM alert "Multiple forward and backward goto statements".
**Test plan**
Make and make test, or white-box test.
...
=> Remove a goto

.gitignore
After make and make test, there are untracked files.
**Test plan**
Make and make test, no more garbage.
...
=> Modify gitignore for macOS

src/query.c
After copying those stuff, the pointer should only move forward by 1.
**Test plan**
```sh
sdb d 'a="\" "' # OK
sdb d 'a="\""' # Previously says Missing quote
```
...
=> Fix quote after quote bug

meson.build
=> The library is named `sdb`

src/query.c
Not nessesary to decrease and increase quot.
**Test plan**
...
...
=> Simplify code

.gitignore, src/main.c, src/sdb.1, test/suite/run.sh
For speeding upt the r2 build.
This can be later made to accept the new sdb text format with escaping and stuff.
=> Add sdb out.sdb == in1.sdb.txt in2.sdb.txt

meson.build, meson_options.txt, test/unit/meson.build, test/unit/minunit.h, test/unit/test_hash.c, test/unit/test_ls.c, test/unit/test_sdb.c
Also updated `minunit.h` with the changes we had in r2 over time.
**Test plan**
Build with meson, then `ninja test` will run the tests.
=> Add Unit Tests to Meson and fix some Warnings

src/ls.c
It's been almost 10 years since this sad little function prototype has been lonely in the header without an implementation. Time to change this! (Also I need it)
=> Implement ls_clone

src/text.c
Otherwise the file will have perms 000
=> Fix perms when saving Text File

README.md, src/sdb.c
https://github.com/radareorg/radare2/issues/17814
https://ci.appveyor.com/project/radareorg/radare2/branch/master/job/te1llyok9ft5wnc6?fullLog=true
https://ci.appveyor.com/project/eagleoflqj/radare2/builds/36062736/job/05g6wxhptewj6rcc?fullLog=true
No C4090 for sdb.
I also update the badge (old link isn't accessible), but it seems appveyor is disabled for this repo.
**Test plan**
...
...
=> Fix msvc warning

Makefile
=> fix install

src/set.c, src/set.h
=> Add API to iterate over SetP and SetU

.github/workflows/ci.yml, src/types.h, test/expire.c, test/stress1.c, test/unit/test_sdb.c
=> Rip windows fixes from Rizin and improve them a bit

src/text.c
=> Use functions instead of multiline macros in text.c

src/json.c, src/main.c, src/query.c, src/types.h, test/fmt.c, test/unit/minunit.h
=> Use stdint types

src/main.c
=> Check for return value in the ftruncate call

src/main.c
=> Error checking when writing to stdout

src/sdb.c
to avoid failure allocation
**Checklist**
=> check the return of calloc

.github/workflows/ci.yml
=> Test python3 bindings

.github/workflows/ci.yml, Makefile, src/sdb.c, src/sdb.h, src/util.c, test/Makefile, test/api/Makefile, test/nset.c
=> Implement numeric key apis

src/main.c
=> Fix zig translate-c because of a bug mixing ints and bools

Makefile
=> Partially fix installation

src/main.c
=> Fix leaks in sdb -G

include/sdb/asserts.h
=> Fix name clash in r2

include/sdb/cwisstable.h
=> Fix big-endian incompatibility in cwisstable

include/sdb/cwisstable.h
=> Fixes to make cwisstable build on macppc

Makefile, src/heap.c
=> Fix heap bug

autogen.sh, config.mk, meson.build, meson_options.txt
=> Meson simplifications, remove python dependency

include/sdb/sdb.h, meson.build, src/Makefile, src/cgen.c, src/main.c
=> Move some cgen/gperf code outside the main

src/tool.c
=> Check for return value in mkdir
